/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Ent as PrismaEnt } from "@prisma/client";

export class EntServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.EntCountArgs, "select">): Promise<number> {
    return this.prisma.ent.count(args);
  }

  async ents(args: Prisma.EntFindManyArgs): Promise<PrismaEnt[]> {
    return this.prisma.ent.findMany(args);
  }
  async ent(args: Prisma.EntFindUniqueArgs): Promise<PrismaEnt | null> {
    return this.prisma.ent.findUnique(args);
  }
  async createEnt(args: Prisma.EntCreateArgs): Promise<PrismaEnt> {
    return this.prisma.ent.create(args);
  }
  async updateEnt(args: Prisma.EntUpdateArgs): Promise<PrismaEnt> {
    return this.prisma.ent.update(args);
  }
  async deleteEnt(args: Prisma.EntDeleteArgs): Promise<PrismaEnt> {
    return this.prisma.ent.delete(args);
  }
}
