/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Ent } from "./Ent";
import { EntCountArgs } from "./EntCountArgs";
import { EntFindManyArgs } from "./EntFindManyArgs";
import { EntFindUniqueArgs } from "./EntFindUniqueArgs";
import { CreateEntArgs } from "./CreateEntArgs";
import { UpdateEntArgs } from "./UpdateEntArgs";
import { DeleteEntArgs } from "./DeleteEntArgs";
import { EntService } from "../ent.service";
@graphql.Resolver(() => Ent)
export class EntResolverBase {
  constructor(protected readonly service: EntService) {}

  async _entsMeta(
    @graphql.Args() args: EntCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Ent])
  async ents(@graphql.Args() args: EntFindManyArgs): Promise<Ent[]> {
    return this.service.ents(args);
  }

  @graphql.Query(() => Ent, { nullable: true })
  async ent(@graphql.Args() args: EntFindUniqueArgs): Promise<Ent | null> {
    const result = await this.service.ent(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Ent)
  async createEnt(@graphql.Args() args: CreateEntArgs): Promise<Ent> {
    return await this.service.createEnt({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Ent)
  async updateEnt(@graphql.Args() args: UpdateEntArgs): Promise<Ent | null> {
    try {
      return await this.service.updateEnt({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Ent)
  async deleteEnt(@graphql.Args() args: DeleteEntArgs): Promise<Ent | null> {
    try {
      return await this.service.deleteEnt(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
