/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { EntService } from "../ent.service";
import { EntCreateInput } from "./EntCreateInput";
import { Ent } from "./Ent";
import { EntFindManyArgs } from "./EntFindManyArgs";
import { EntWhereUniqueInput } from "./EntWhereUniqueInput";
import { EntUpdateInput } from "./EntUpdateInput";

export class EntControllerBase {
  constructor(protected readonly service: EntService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Ent })
  async createEnt(@common.Body() data: EntCreateInput): Promise<Ent> {
    return await this.service.createEnt({
      data: data,
      select: {
        createdAt: true,
        details: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Ent] })
  @ApiNestedQuery(EntFindManyArgs)
  async ents(@common.Req() request: Request): Promise<Ent[]> {
    const args = plainToClass(EntFindManyArgs, request.query);
    return this.service.ents({
      ...args,
      select: {
        createdAt: true,
        details: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Ent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async ent(@common.Param() params: EntWhereUniqueInput): Promise<Ent | null> {
    const result = await this.service.ent({
      where: params,
      select: {
        createdAt: true,
        details: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Ent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateEnt(
    @common.Param() params: EntWhereUniqueInput,
    @common.Body() data: EntUpdateInput
  ): Promise<Ent | null> {
    try {
      return await this.service.updateEnt({
        where: params,
        data: data,
        select: {
          createdAt: true,
          details: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Ent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteEnt(
    @common.Param() params: EntWhereUniqueInput
  ): Promise<Ent | null> {
    try {
      return await this.service.deleteEnt({
        where: params,
        select: {
          createdAt: true,
          details: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
